#name: Publish Alibaba
#
#on:
#  workflow_dispatch:
#  push:
#    branches:
#      - master
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v1
#
#      - name: Set up JDK
#        uses: actions/setup-java@v2
#        with:
#          distribution: 'adopt'
#          java-version: '11'
#          server-id: maven
#          server-username: MAVEN_USERNAME
#          server-password: MAVEN_PASSWORD
#          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
#          gpg-passphrase: MAVEN_GPG_PASSPHRASE
#
#      - name: Publish Package Registry
#        run: |
#          RELEASE_REPO="\${env.MAVEN_SERVER_ID}::default::\${env.RELEASE_URL}"
#          mvn --batch-mode deploy -P release -DaltDeploymentRepository="${RELEASE_REPO}" -DskipTests
#        env:
#          RELEASE_URL: https://packages.aliyun.com/maven/repository/2026582-release-AuUWIo
#          MAVEN_SERVER_ID: maven
#          MAVEN_USERNAME: 5f3fc340209ad8bf48f5dd13
#          MAVEN_PASSWORD: ${{ secrets.ALIYUN_PASSWORD }}
#          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
#
